### ISSUE TITLE
Translate documentation into other languages

### ISSUE THREAD

**Issue by RameshAditya** [RameshAditya/asciify#11]
If you're fluent in languages other than English, feel free to submit a PR with the README file translated into your favorite language. 🙂 

Languages covered so far - 
* English 
* French
* Greek

If you're familiar with another language, go right ahead and fork this repo and start contributing! :)

**Comment by danielbenedi6** [comment]
Hey! I translated the README to my mother tonge, Spanish. Here is it for you:
[README-es.txt](https://github.com/RameshAditya/asciify/files/2463664/README-es.txt)

**Comment by Andrey-Raspopov** [comment]
Good morning!
I'm going to translate it to russian, commenting to avoid any conflicts.

**Comment by RameshAditya** [comment]
@danielbenedi6 Could you please enclose your work as a pull request? It'd make merging convenient. If you're new to this, there are plenty of resources on how to submit a pull request. 😄 



@Andrey-Raspopov Awesome! It's all yours. 😄

**Comment by erNail** [comment]
Hi, i'd translate it to German today in the late evening 👍. Just commenting to prevent conflicts.

**Comment by RameshAditya** [comment]
@erNail Sounds good! 🙂

**Comment by theovasi** [comment]
Hello, I am going to translate the README to Greek.

**Comment by wdhif** [comment]
@RameshAditya Hi, I will translate it in French.

**Comment by RameshAditya** [comment]
@theovasi @wdhif noted! :slightly_smiling_face:

**Comment by wdhif** [comment]
@RameshAditya Here you go: https://github.com/RameshAditya/asciify/pull/13

**Comment by RameshAditya** [comment]
@pazui Alright! :slightly_smiling_face:

**Comment by onlurking** [comment]
Hello, I'll translate it to Brazillian Portuguese.

**Comment by JaneLiuUSA** [comment]
I'll translate to Traditional Mandarin Chinese.

**Comment by sichuan-pepper** [comment]
I'll translate to Japanese.

**Comment by dafinoer** [comment]
I'll translate to indonesia

**Comment by tribakzero** [comment]
Translated to spanish :)

**Comment by jcezarms** [comment]
Translated to Brazillian Portuguese at #23! \o

**Comment by tomial** [comment]
Translated to Simplified Chinese :smile: #30
