### ISSUE TITLE
ValueError: height and width must be > 0

### ISSUE THREAD

**Issue by repodevs** [RameshAditya/asciify#3]
Trying convert Image [7319167558_9ac77e8a54_b.jpg](https://user-images.githubusercontent.com/13567128/44579724-88c5ef00-a7c1-11e8-9efc-5b5428b39a0f.jpg) to ASCII get this error
```python
$ python asciify.py 7319167558_9ac77e8a54_b.jpg
Traceback (most recent call last):
  File "asciify.py", line 86, in <module>
    runner(path)
  File "asciify.py", line 65, in runner
    image = do(image)
  File "asciify.py", line 40, in do
    image = resize(image)
  File "asciify.py", line 16, in resize
    new_image = image.resize(new_dim)
  File "/home/repodevs/.virtualenvs/asciify/local/lib/python2.7/site-packages/PIL/Image.py", line 1765, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
```

**Comment by RameshAditya** [comment]
@repodevs Hm, that's odd. I tried running the script on the same picture and had no errors.

Here was my output - ![](https://i.imgur.com/CsVDW6F.png) 

https://imgur.com/CsVDW6F

I see that you're running it on Python 2.7, right? 

I executed my script on Python 3.6.1.

I verified this by running ```python --version``` on the terminal. Perhaps, you should try executing the script on the same version.

**Comment by JohnF8** [comment]
I had this same issue and I was using Python 2.7. When I ran with python 3 it worked.

**Comment by davechen1** [comment]
![image](https://user-images.githubusercontent.com/42885520/46148266-40a35c00-c29a-11e8-9c7a-bb51b8721823.png)
Hi why my img is so ugly and don't like yours?

**Comment by RameshAditya** [comment]
@davechen1 I'm unsure what you mean - your output matches my output from the GIF in the readme. 

If you're referencing the text version of the image I've added below the GIF, I had to remove a few lines to fit the ascii-fied image into the screen so it may not look the same. 

Your output is exactly the same as mine is supposed to be. :slightly_smiling_face:
